### ISSUE TITLE
Troubles downloading .mp3 file

### ISSUE THREAD

**Issue by fabriziojpiva** [s3condAtall/Deezloader#3]
Hi s3condAtall, I'm on Debian 8.6 jessie x64. Node js: v4.6.0. Firefox ESR 45.3.0. Deezloader runs perfect, but my problem arises when downloading a song, because it downloads me the cover in /Deezloader/img but there is no .mp3 file in Deezloader/mp3. I thought it was that song I was trying to get, but it still not working with any song.

**Comment by s3condAtall** [comment]
For linux, try this:
https://mega.nz/#!hNEniShL

It already includes a nodejs binary, just launch the start.sh included as well..

**Comment by fabriziojpiva** [comment]
It works perfect! You should upload it on the repo so that every linux user can use it. Thank you so much!
