### ISSUE TITLE
Deezloader not downloading MP3 files

### ISSUE THREAD

**Issue by nullencio** [s3condAtall/Deezloader#5]
Apparently it's a common issue with many Linux (and some Mac) users; is there a way to fix it? Why is the reason this happens? Do I need to update my Node.js installed version or install an additional dependence?

By the way, how do I enable verbosity on app to watch errors and warnings? Could be helpful trying to solve this error.

**Comment by painlessjeff** [comment]
I was having this issue too using Arch Linux. I solved it by using nodejs-lts version.

**Comment by s3condAtall** [comment]
Solution [here](https://github.com/s3condAtall/Deezloader/issues/3)
